version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    rebase-strategy: auto
    pull-request-branch-prefix: "dependabot/"
