name: Lint Check

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  check:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out project
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js 14
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '14'

      - name: Install dependencies and run lint
        run: |
          cd build-tools
          npm ci
          npm run gulp lint
