name: Sonar Cloud - Quality Gate

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v4.2.1
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@v1.1.0

      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
       SONAR_HOST_URL: ${{ secrets.SONAR_CLOUD_URL }}

    - name: "Quality Gate Status value"
      run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
