name: Sonar Cloud Scan

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v4.2.1
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: SonarQube Scan
      uses: warchant/setup-sonar-scanner@v7

    - name: SonarQube Scan
      run: sonar-scanner
           -Dsonar.host.url=${{ secrets.SONAR_CLOUD_URL }}
           -Dsonar.login=${{ secrets.SONAR_CLOUD_TOKEN }}
           -Dsonar.organization=${{ secrets.SONAR_CLOUD_ORGANIZATION }}
           -Dsonar.projectKey=${{ secrets.SONAR_CLOUD_PROJECT_KEY }}
           -Dsonar.sources=src/
           -Dsonar.java.binaries=target/test-classes/com/kiroule/vaadin/bakeryapp
          # -Dsonar.sources=$GITHUB_WORKSPACE
